exports.UserRole = {
  ADMIN: "ADMIN",
  OPERATOR: "OPERATOR",
  PROVIDER: "PROVIDER",
  WORKER: "WORKER",
};

exports.BookingStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
